env:
    commonjs: true
    es6: true
    node: true
extends:
    - standard
globals:
    Atomics: readonly
    SharedArrayBuffer: readonly
parserOptions:
    ecmaVersion: 2018
ignorePatterns:
    - dist
rules:
    semi: [2, 'always']
    quotes: [2, 'single']
    indent: [2, 4, { 'SwitchCase': 1 }]
    comma-dangle: ['error', 'only-multiline']
    brace-style: [2, 'stroustrup', { 'allowSingleLine': true }]
